### ISSUE TITLE
Wrong parameters for get_network_resources_facts()

### ISSUE THREAD

**Issue by john-colgrave** [ansible-network/resource_module_builder#71]
I am new to Ansible and this resource module builder. I tried to build a resource module using a copy of the sample model with a few tweaks but when I try and use the generated collection I get the error:
TypeError: get_network_resources_facts() takes from 2 to 4 positional arguments but 5 were given

The generated code in question is in .../module_utils/network/mqaos/facts/facts.py where mqaos is my collection name, and seems to be:
```
netres_choices = FactsArgs.argument_spec['gather_network_resources'].get('choices', [])
if self.VALID_RESOURCE_SUBSETS:
    self.get_network_resources_facts(netres_choices, FACT_RESOURCE_SUBSETS, resource_facts_type, data)
```

If I remove the entries_choices argument then I do not get the error.

**Comment by lcphill** [comment]
Hi,

I am experiencing the same issue. I was able to push ahead by commenting out the first method argument (i.e., 'netres_choices').

Thank you for taking the lead on filing the issue.

**Comment by john-colgrave** [comment]
It seems unlikely that this issue will be fixed. I have started using the latest content builder: https://github.com/ansible-community/ansible.content_builder
